language: python
python:
  - "3.6"

install:
    - sudo apt-get update
    - ./configurations/travis_miniconda.sh
    - PATH="$HOME/miniconda/bin:$PATH"
    - conda env create -f configurations/environment.yml

script:
    - conda activate ekw-data
    - python create

after_success:
    - codecov
